// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbjpS0pvDAHh9D3jjlOwi94diWzCImqUk',
    appId: '1:774704709066:web:ccc26a04c8ca98bd832333',
    messagingSenderId: '774704709066',
    projectId: 'friendiary-krrg',
    authDomain: 'friendiary-krrg.firebaseapp.com',
    storageBucket: 'friendiary-krrg.appspot.com',
    databaseURL: 'https://friendiary-krrg-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5c32Gthryl0y8H7Zl3eOjFaFUPyk0U-0',
    appId: '1:774704709066:android:e934a4c351ee853c832333',
    messagingSenderId: '774704709066',
    projectId: 'friendiary-krrg',
    storageBucket: 'friendiary-krrg.appspot.com',
    databaseURL: 'https://friendiary-krrg-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeUI7BXBireo7r4b9QaPmBG82wUF44Z1I',
    appId: '1:774704709066:ios:bba84c746fe9a053832333',
    messagingSenderId: '774704709066',
    projectId: 'friendiary-krrg',
    storageBucket: 'friendiary-krrg.appspot.com',
    iosBundleId: 'com.example.proj',
    databaseURL: 'https://friendiary-krrg-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeUI7BXBireo7r4b9QaPmBG82wUF44Z1I',
    appId: '1:774704709066:ios:bba84c746fe9a053832333',
    messagingSenderId: '774704709066',
    projectId: 'friendiary-krrg',
    storageBucket: 'friendiary-krrg.appspot.com',
    iosBundleId: 'com.example.proj',
    databaseURL: 'https://friendiary-krrg-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbjpS0pvDAHh9D3jjlOwi94diWzCImqUk',
    appId: '1:774704709066:web:18c9a93a47c4cd0a832333',
    messagingSenderId: '774704709066',
    projectId: 'friendiary-krrg',
    authDomain: 'friendiary-krrg.firebaseapp.com',
    storageBucket: 'friendiary-krrg.appspot.com',
    databaseURL: 'https://friendiary-krrg-default-rtdb.europe-west1.firebasedatabase.app/',
  );
}
